apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: to-do-postgres-backup-pvc
  namespace: to-do
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
